version: "2"
services:
  mysql-service:
    image: mysql:8
    container_name: mysql-service
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    networks:
      - musala-network
  java-drone-service:
    image: java-drone-image
    build: java/.
    container_name: java-drone-service
    ports:
      - "8080:8080"
    networks:
      - musala-network
    depends_on:
      - mysql-service
  node-drone-service:
    image: node-drone-image
    build: node/.
    container_name: node-drone-service
    networks:
      - musala-network
    ports:
      - "8000:80"
    environment:
      - NODE_PATH=.
      - PORT=80
      - NODE_ENV=development
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=node-drones
      - DB_HOST=mysql-service
    volumes:
      - ./node:/home/node
      - ./node/bin/log:/var/log/application/node_drones
    depends_on:
      - mysql-service
networks:
  musala-network:
